{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shelf/3.1.0/shelf-3.1.0.module",
    "group": "com.toddway.shelf",
    "module": "shelf",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "shelf.klib",
          "url": "shelf-iossimulatorarm64-3.1.0.klib",
          "size": 44140,
          "sha512": "84e4ed400782218eab96238f4850441d5a016d03f15c4e3bb3652943f8a32878b19eaa0b76085402666d26ee7f1eba956e3bfd9c3d22c4c9273e96e5484d8f88",
          "sha256": "aa5498d911669dfaced954b0f0312ad68578e0823816faec819b20ea09e4cb4b",
          "sha1": "f6062723884ea1dd495d724e368bff4bfeca9749",
          "md5": "83e7ba15e0de545ea2e7ebbf514d90bb"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "shelf-iossimulatorarm64-3.1.0-sources.jar",
          "url": "shelf-iossimulatorarm64-3.1.0-sources.jar",
          "size": 11596,
          "sha512": "f3c5a775f239ef6378cd8f8317d480e9f157e600683887d7555f58784d67a58bcd74864320ba84abb28e9e9581f9bbbef0f22998f4107ffd1f1bb6c0321d2d00",
          "sha256": "88bdee79988ca0a8bacc2f61b4d2a1f595ec7e37cbf37393e359c02edd4371c0",
          "sha1": "1c3401a78f0be70379bfea80b35aa7796ca61971",
          "md5": "83abb0773c33befae754712806faf9ae"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "shelf-iossimulatorarm64-3.1.0-metadata.jar",
          "url": "shelf-iossimulatorarm64-3.1.0-metadata.jar",
          "size": 3162,
          "sha512": "b0901b0fa928c5e1c2a9319a7d9866996b1ce184844c7e655307a12c2cb024ebff9a3799f78d995dd66f3aebf69f2a639dc155fb01838ab7e787b0fb21ed90cc",
          "sha256": "abf2e75b0eeba4b9503bdff108d45a8ddc688595339f0b5a021afead94469559",
          "sha1": "517f6b2dc8c929df710c98e87d5d18291957dc60",
          "md5": "ef4dccfbf6c47d8eb464a653f7c3c719"
        }
      ]
    }
  ]
}
