{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shelf-coroutines/3.0.0/shelf-coroutines-3.0.0.module",
    "group": "com.toddway.shelf",
    "module": "shelf-coroutines",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.toddway.shelf",
          "module": "shelf",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "shelf-coroutines-js-3.0.0.klib",
          "url": "shelf-coroutines-js-3.0.0.klib",
          "size": 7055,
          "sha512": "48d7911307370312c6294441c779b44bf9ea8a923b08b78e09f9299eee0c0a4b07da16707e896cab13b7059798c1e260de71c4a2f91129dc4bed239d01395436",
          "sha256": "295955cbaa300f42e8b0e4754342e674fb41260877126d53e2b3771a83d12948",
          "sha1": "b108cd75e25e1006398b246c50a708965f201f00",
          "md5": "dec5bf6831eba7433e21aecf2759a57b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.toddway.shelf",
          "module": "shelf",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "shelf-coroutines-js-3.0.0.klib",
          "url": "shelf-coroutines-js-3.0.0.klib",
          "size": 7055,
          "sha512": "48d7911307370312c6294441c779b44bf9ea8a923b08b78e09f9299eee0c0a4b07da16707e896cab13b7059798c1e260de71c4a2f91129dc4bed239d01395436",
          "sha256": "295955cbaa300f42e8b0e4754342e674fb41260877126d53e2b3771a83d12948",
          "sha1": "b108cd75e25e1006398b246c50a708965f201f00",
          "md5": "dec5bf6831eba7433e21aecf2759a57b"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "shelf-coroutines-js-3.0.0-sources.jar",
          "url": "shelf-coroutines-js-3.0.0-sources.jar",
          "size": 1619,
          "sha512": "66b1d735eb5b2c460cda1aff125a8af70dfc3650ca5598816520776928d7118f734a7838bcc4c56e2d2650d1815685191a872002817f19ad5f00f31b92476622",
          "sha256": "e24a2120fc3e61a6e7cad8f9f0f4a985f4b9638b2a56238996676a37f8f76b91",
          "sha1": "be072b848b5c28d64b10e4447350c27806a011b5",
          "md5": "b3f1e497c446af61cbe96b9b835c7484"
        }
      ]
    }
  ]
}
