{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shelf-coroutines/3.0.0/shelf-coroutines-3.0.0.module",
    "group": "com.toddway.shelf",
    "module": "shelf-coroutines",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.toddway.shelf",
          "module": "shelf",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "shelf-coroutines.klib",
          "url": "shelf-coroutines-iossimulatorarm64-3.0.0.klib",
          "size": 8201,
          "sha512": "0ecdd4de515b66390ccfba7bb0013f629f224fb9e899652226f972cd159a2c9262d2b60aec4aeba7ce48e678264bc5e3c22ebf30e9c594076cbf64ca3aa50883",
          "sha256": "aff108ef0f14c4badbc145231a15accdc21e527582ac6b110fede0de2e211a8e",
          "sha1": "24ee32655732a65cb9e4f22c7af3989ec1bded23",
          "md5": "8a3e1244dbfaac6aed8c17424ad0b94b"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "shelf-coroutines-iossimulatorarm64-3.0.0-sources.jar",
          "url": "shelf-coroutines-iossimulatorarm64-3.0.0-sources.jar",
          "size": 1619,
          "sha512": "66b1d735eb5b2c460cda1aff125a8af70dfc3650ca5598816520776928d7118f734a7838bcc4c56e2d2650d1815685191a872002817f19ad5f00f31b92476622",
          "sha256": "e24a2120fc3e61a6e7cad8f9f0f4a985f4b9638b2a56238996676a37f8f76b91",
          "sha1": "be072b848b5c28d64b10e4447350c27806a011b5",
          "md5": "b3f1e497c446af61cbe96b9b835c7484"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.toddway.shelf",
          "module": "shelf",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "shelf-coroutines-iossimulatorarm64-3.0.0-metadata.jar",
          "url": "shelf-coroutines-iossimulatorarm64-3.0.0-metadata.jar",
          "size": 261,
          "sha512": "8be4b76ae3fb4983db4a56dbf4142ce256521f19920e15b44dbb06f48ec543b48cd3f02da2424782920747b37c9ce954896b04c6b86c1a06e15256a7718daec0",
          "sha256": "c0900e8e2ff21a946c1fb9d58a1f6f5186d95540970614750a6e70e530d2e303",
          "sha1": "977a110a6fdfcda3d529f51354d362a13e75f709",
          "md5": "7bd6aca5d0c506ea26a987f6afa5b320"
        }
      ]
    }
  ]
}
