{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shelf/3.1.0/shelf-3.1.0.module",
    "group": "com.toddway.shelf",
    "module": "shelf",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "shelf-jvm-3.1.0.jar",
          "url": "shelf-jvm-3.1.0.jar",
          "size": 44357,
          "sha512": "c900d6684bd43819f12c4839d3257be599bee71050b1ff5e234d82005a0705ad1faab9df847c55a271357ff400a9e0d3c3ad0e9813fbb33baded988c5a2cf384",
          "sha256": "9105a729370bf73243a52325692f6aed42093c7650d53239b44b22c6ec2d0e4c",
          "sha1": "6a89dce3e668f596949592f42a82a5ee062bda8e",
          "md5": "795f404f3d64b49e6d867066e764a244"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "shelf-jvm-3.1.0.jar",
          "url": "shelf-jvm-3.1.0.jar",
          "size": 44357,
          "sha512": "c900d6684bd43819f12c4839d3257be599bee71050b1ff5e234d82005a0705ad1faab9df847c55a271357ff400a9e0d3c3ad0e9813fbb33baded988c5a2cf384",
          "sha256": "9105a729370bf73243a52325692f6aed42093c7650d53239b44b22c6ec2d0e4c",
          "sha1": "6a89dce3e668f596949592f42a82a5ee062bda8e",
          "md5": "795f404f3d64b49e6d867066e764a244"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "shelf-jvm-3.1.0-sources.jar",
          "url": "shelf-jvm-3.1.0-sources.jar",
          "size": 13334,
          "sha512": "b39457dad0100f91680fa03f1c5696ff65d35ffa34f2e7e28662591b17b7a7352d1326ef42992aa1110c4f2e58be85f9d6fce1eaf430f6cb7e902c6d93cbf17d",
          "sha256": "1cc388b452b96eff5c2299c10de88c0a1a0071368645fb5df4cfdc94bcfd53b1",
          "sha1": "9c1b1ad9b56b2ea3f95ce4e3f04002241781d0bf",
          "md5": "069e00b48cb711b924b1212660e8d8c9"
        }
      ]
    }
  ]
}
