{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shelf-coroutines/3.0.0/shelf-coroutines-3.0.0.module",
    "group": "com.toddway.shelf",
    "module": "shelf-coroutines",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.toddway.shelf",
          "module": "shelf",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "shelf-coroutines.klib",
          "url": "shelf-coroutines-iosx64-3.0.0.klib",
          "size": 8098,
          "sha512": "f92aedc5c90afa2708b44ac7a172c0fb911b0c8f33e8ea36f12454962a1e1c3267379f56bc79ac7395540177edd4dbf48fc724d8c9a13f411f7606b59ba7be1c",
          "sha256": "487628fcde1140e127aff6b979910ff540c8783ce09b174ac5523a1eed121d14",
          "sha1": "66ae584ccd18e828c7d707622980a6029ca99458",
          "md5": "57f0f03dc330ea6590e06f7cf2eda879"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "shelf-coroutines-iosx64-3.0.0-sources.jar",
          "url": "shelf-coroutines-iosx64-3.0.0-sources.jar",
          "size": 1619,
          "sha512": "66b1d735eb5b2c460cda1aff125a8af70dfc3650ca5598816520776928d7118f734a7838bcc4c56e2d2650d1815685191a872002817f19ad5f00f31b92476622",
          "sha256": "e24a2120fc3e61a6e7cad8f9f0f4a985f4b9638b2a56238996676a37f8f76b91",
          "sha1": "be072b848b5c28d64b10e4447350c27806a011b5",
          "md5": "b3f1e497c446af61cbe96b9b835c7484"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.toddway.shelf",
          "module": "shelf",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "shelf-coroutines-iosx64-3.0.0-metadata.jar",
          "url": "shelf-coroutines-iosx64-3.0.0-metadata.jar",
          "size": 261,
          "sha512": "8be4b76ae3fb4983db4a56dbf4142ce256521f19920e15b44dbb06f48ec543b48cd3f02da2424782920747b37c9ce954896b04c6b86c1a06e15256a7718daec0",
          "sha256": "c0900e8e2ff21a946c1fb9d58a1f6f5186d95540970614750a6e70e530d2e303",
          "sha1": "977a110a6fdfcda3d529f51354d362a13e75f709",
          "md5": "7bd6aca5d0c506ea26a987f6afa5b320"
        }
      ]
    }
  ]
}
