{
  "formatVersion": "1.1",
  "component": {
    "url": "../../shelf/3.0.0/shelf-3.0.0.module",
    "group": "com.toddway.shelf",
    "module": "shelf",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "shelf-jvm-3.0.0.jar",
          "url": "shelf-jvm-3.0.0.jar",
          "size": 38214,
          "sha512": "411bd266d3cb6d4bb275e02574172e38caf02a28422f9c69bf057b2af9379ccee78621659ba14e7a2931dbff3fcc9a72caf23c6f1b080767492a115f0a2acb27",
          "sha256": "9b287bb1a57523eceee349bf543c42db3f85dfd89a6d814e5c550fae0fee784b",
          "sha1": "016e02eeb51a8f2f300b55e1edd8eeeb3f1e4c14",
          "md5": "5155915377838dbfc9dcf7d5b53e7b27"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "shelf-jvm-3.0.0.jar",
          "url": "shelf-jvm-3.0.0.jar",
          "size": 38214,
          "sha512": "411bd266d3cb6d4bb275e02574172e38caf02a28422f9c69bf057b2af9379ccee78621659ba14e7a2931dbff3fcc9a72caf23c6f1b080767492a115f0a2acb27",
          "sha256": "9b287bb1a57523eceee349bf543c42db3f85dfd89a6d814e5c550fae0fee784b",
          "sha1": "016e02eeb51a8f2f300b55e1edd8eeeb3f1e4c14",
          "md5": "5155915377838dbfc9dcf7d5b53e7b27"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "shelf-jvm-3.0.0-sources.jar",
          "url": "shelf-jvm-3.0.0-sources.jar",
          "size": 10697,
          "sha512": "78f17cba2b851e48abbca0f4f50f978b9ecf6739676cf4b65cec3c721a1e7902e15c27b6a963ce9549d4d351bb7ee518f6308fea16f496b9e10ffa0bd4a6a093",
          "sha256": "25d833a7796ea0a309d3d9e2191037ecd9a7b1011805a9ffc04acd319d2d3673",
          "sha1": "f6cc0b36125e7a1a0b78927233b1791bc828a58f",
          "md5": "50a6db6ba9bbd65309b01b659d1556eb"
        }
      ]
    }
  ]
}
